### ISSUE TITLE
执行 consult.php 报错 `Undefined property` && `Invalid argument supplied for foreach()`

### ISSUE THREAD

**Issue by jacobwwang** [279838089/meican#2]
环境：
`
[meican]# php -v
PHP 5.6.30 (cli) (built: Jan 19 2017 08:00:02)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.4, Copyright (c) 2002-2017, by Derick Rethans
`

错误信息：
`
[meican]# php consult.php > 1.html
PHP Notice:  Undefined property: stdClass::$name in ./meican/consult.php on line 20
PHP Stack trace:
PHP   1. {main}() ./meican/consult.php:0
PHP Notice:  Undefined property: stdClass::$dishList in ./meican/consult.php on line 22
PHP Stack trace:
PHP   1. {main}() ./meican/consult.php:0
PHP Warning:  Invalid argument supplied for foreach() in ./meican/consult.php on line 22
PHP Stack trace:
PHP   1. {main}() ./meican/consult.php:0
PHP Notice:  Undefined property: stdClass::$name in ./meican/consult.php on line 20
PHP Stack trace:
PHP   1. {main}() ./meican/consult.php:0
PHP Notice:  Undefined property: stdClass::$dishList in ./meican/consult.php on line 22
PHP Stack trace:
PHP   1. {main}() ./meican/consult.php:0
PHP Warning:  Invalid argument supplied for foreach() in ./meican/consult.php on line 22
PHP Stack trace:
PHP   1. {main}() ./meican/consult.php:0
PHP Notice:  Undefined property: stdClass::$name in ./meican/consult.php on line 20
PHP Stack trace:
PHP   1. {main}() ./meican/consult.php:0
PHP Notice:  Undefined property: stdClass::$dishList in ./meican/consult.php on line 22
PHP Stack trace:
PHP   1. {main}() ./meican/consult.php:0
PHP Warning:  Invalid argument supplied for foreach() in ./meican/consult.php on line 22
PHP Stack trace:
PHP   1. {main}() ./meican/consult.php:0
PHP Notice:  Undefined property: stdClass::$name in ./meican/consult.php on line 20
PHP Stack trace:
PHP   1. {main}() ./meican/consult.php:0
PHP Notice:  Undefined property: stdClass::$dishList in ./meican/consult.php on line 22
PHP Stack trace:
PHP   1. {main}() ./meican/consult.php:0
PHP Warning:  Invalid argument supplied for foreach() in ./meican/consult.php on line 22
PHP Stack trace:
PHP   1. {main}() ./meican/consult.php:0
`

**Comment by 279838089** [comment]
版本已经更新，可以自动点其他人点的餐，你更新一下，看下日志

**Comment by jacobwwang** [comment]
代码已更新至最新版。
主要还是想自己指定菜单，而不是点其他人的餐

**Comment by 279838089** [comment]
一些店下线了，明天更新一下

**Comment by 279838089** [comment]
更新到最新版，已经修复
